remote_theme: kitian616/jekyll-TeXt-theme
text_skin: dark
highlight_theme: tomorrow-night

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-octicons

title: Bion App
description: Mathematical modeling app for fed-batch bioractors

